---
title: "NY NOAA Weather Data Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill

---


```{r setup, include=FALSE}
library(tidyverse)
library(lubridate)
library(plotly)
library(p8105.datasets)
library(flexdashboard)

```



```{r, include=FALSE}
nynoaadat = read.csv("nynoaadat.csv")

nynoaa_clean = nynoaadat |>
  filter(!is.na(tmax), !is.na(tmin)) |>
  mutate(
    year = lubridate::year(date),
    month = lubridate::month(date, label = TRUE),
    day = lubridate::day(date)
  )

# Sample data for faster loading
set.seed(123)
nynoaadat_sample = sample_n(nynoaa_clean, 1000)
```

Column {data-width=500}
-----------------------------------------------------------------------


### Chart A

```{r, echo=FALSE, message=FALSE, warning=FALSE}

plot_ly(
  data = nynoaadat_sample |> 
    group_by(date) |> 
    summarise(mean_snow = mean(snow, na.rm = TRUE)),
  x = ~date,
  y = ~mean_snow,
  type = 'scatter',
  mode = 'lines',
  line = list(width = 1.5, color = 'orange')
) |>
  layout(
    title = "Average Daily Snowfall (mm)",
    xaxis = list(title = "Date"),
    yaxis = list(title = "Snowfall (mm)")
  )
```


Column {data-width=500}
-----------------------------------------------------------------------


### Chart B

```{r, echo=FALSE, message=FALSE, warning=FALSE}
plot_ly(
  data = nynoaadat_sample |>
    group_by(month) |>
    summarise(total_prcp = sum(prcp, na.rm = TRUE)),
  x = ~month,
  y = ~total_prcp,
  type = 'bar',
  marker = list(color = 'pink')) |>
  layout(
    title = "Total Monthly Precipitation",
    xaxis = list(title = "Month (from year 1981–2010)"),
    yaxis = list(title = "Total Precipitation (mm)")
  )
```

### Chart C
```{r, echo=FALSE, message=FALSE, warning=FALSE}
#Box Plot – Monthly Temperature Spread
plot_ly(data = nynoaadat_sample,
        x = ~month,
        y = ~tmax,
        type = "box",
        color = ~month,
        jitter = 0.3,
        pointpos = -1.8) |>
  layout(
    title = "Distribution of Daily Max Temperature by Month",
    xaxis = list(title = "Month(from year 1981–2010)"),
    yaxis = list(title = "Max Temperature (°C)"))
```



